### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by yotamco100**
Lol i had to make these changes

### CODE REVIEW

**Comment by edocod** [comment]
This patch makes the project not compile. Please check your changes (and privilege, while you're at it).

**Comment by s0r00t** [comment]
fuck the one of you who got me banned

**Comment by edocod** [comment]
But it was fun

**Comment by yotamco100** [comment]
Bruh... S0root, its a prank... We can join now, its been 24 hours... Its not permaban

**Comment by edocod** [comment]
... Just a prank bro! Jkjk

**Pull request closed without merging**
